name: External Use

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tima-test:
    name: tima-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: r-lib/actions/setup-r@v1
      - if: matrix.os == 'windows-latest'
        run: |
          choco install curl
          choco install gzip
          choco install unzip
          choco install wget
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          mamba-version: "*"
          channels: conda-forge, bioconda, defaults
          channel-priority: true
          activate-environment: base
          environment-file: environment.yml
      - uses: s-weigand/setup-conda@v1
      - name: Run tests
        run: |
          bash tests/integration_test.sh
